apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-1-deployment
  labels:
    app: app-1
spec:
  replicas: 1 # Replika sayısı, preview aşaması için 1 vereceğiz her kullanıcıya.
  selector:
    matchLabels:
      app: app-1
  template:
    metadata:
      labels:
        app: app-1
    spec:
      containers:
      - name: app-1
        image: app-1:12345 
        ports:
        - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: app-1-service
  labels:
    app: app-1
spec:
  selector:
    app: app-1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-1-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: app-1.preview.mindbricks.com # preview.mindbricks.com sabit olacak.
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: app-1-service 
            port:
              number: 80

